Сервис бота. Остов для отправки-получения сообщений
comptech-winter-school/academrecycle pull request #1
Opened 2021-01-31 13:08 UTC by UltimateHikari

простенький эхобот, с локальным запуском по `node index.js`

2021-01-31 18:37 UTC, koteld requested changes
1. Необходимо добавить package.json в git
2. Давай сразу добавим линтер раз уж это первый PR

2021-02-01 04:13 UTC, koteld commented
package.json из корня тогда тоже нужно добавить

2021-02-01 04:19 UTC, UltimateHikari commented
> package.json из корня тогда тоже нужно добавить

А он нам разве нужен? Вроде бы бот и админка разные сущности, да и не будет ли беды для вложенных .json?

2021-02-01 04:46 UTC, koteld commented
Перенеси eslint в devDependencies

2021-02-01 06:37 UTC, koteld approved these changes

2021-02-01 06:37 UTC, merged